export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  API_FAILED: 'API_FAILED',
  CONFIG_MISSING: 'CONFIG_MISSING',
  INVALID_PARAMS: 'INVALID_PARAMS',
  DATA_NOT_FOUND: 'DATA_NOT_FOUND',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  [ERROR_CODES.UNAUTHORIZED]: '未授权，请先登录',
  [ERROR_CODES.API_FAILED]: 'API 请求失败',
  [ERROR_CODES.CONFIG_MISSING]: '配置缺失',
  [ERROR_CODES.INVALID_PARAMS]: '参数无效',
  [ERROR_CODES.DATA_NOT_FOUND]: '数据不存在',
  [ERROR_CODES.NETWORK_TIMEOUT]: '网络请求超时',
  [ERROR_CODES.UNKNOWN]: '未知错误',
};
